package com.sousajrps.covid19pt.remote.mappers

import com.sousajrps.covid19pt.remote.models.Data

object DataMapper {
    private const val DATA = "data"
    private const val DATA_DADOS = "data_dados"
    private const val CONFIRMADOS = "confirmados"
    private const val CONFIRMADOS_ARSNORTE = "confirmados_arsnorte"
    private const val CONFIRMADOS_ARSCENTRO = "confirmados_arscentro"
    private const val CONFIRMADOS_ARSLVT = "confirmados_arslvt"
    private const val CONFIRMADOS_ARSALENTEJO = "confirmados_arsalentejo"
    private const val CONFIRMADOS_ARSALGARVE = "confirmados_arsalgarve"
    private const val CONFIRMADOS_ACORES = "confirmados_acores"
    private const val CONFIRMADOS_MADEIRA = "confirmados_madeira"
    private const val CONFIRMADOS_ESTRANGEIRO = "confirmados_estrangeiro"
    private const val CONFIRMADOS_NOVOS = "confirmados_novos"
    private const val RECUPERADOS = "recuperados"
    private const val OBITOS = "obitos"
    private const val INTERNADOS = "internados"
    private const val INTERNADOS_UCI = "internados_uci"
    private const val LAB = "lab"
    private const val SUSPEITOS = "suspeitos"
    private const val VIGILANCIA = "vigilancia"
    private const val N_CONFIRMADOS = "n_confirmados"
    private const val CADEIAS_TRANSMISSAO = "cadeias_transmissao"
    private const val TRANSMISSAO_IMPORTADA = "transmissao_importada"
    private const val CONFIRMADOS_0_9_F = "confirmados_0_9_f"
    private const val CONFIRMADOS_0_9_M = "confirmados_0_9_m"
    private const val CONFIRMADOS_10_19_F = "confirmados_10_19_f"
    private const val CONFIRMADOS_10_19_M = "confirmados_10_19_m"
    private const val CONFIRMADOS_20_29_F = "confirmados_20_29_f"
    private const val CONFIRMADOS_20_29_M = "confirmados_20_29_m"
    private const val CONFIRMADOS_30_39_F = "confirmados_30_39_f"
    private const val CONFIRMADOS_30_39_M = "confirmados_30_39_m"
    private const val CONFIRMADOS_40_49_F = "confirmados_40_49_f"
    private const val CONFIRMADOS_40_49_M = "confirmados_40_49_m"
    private const val CONFIRMADOS_50_59_F = "confirmados_50_59_f"
    private const val CONFIRMADOS_50_59_M = "confirmados_50_59_m"
    private const val CONFIRMADOS_60_69_F = "confirmados_60_69_f"
    private const val CONFIRMADOS_60_69_M = "confirmados_60_69_m"
    private const val CONFIRMADOS_70_79_F = "confirmados_70_79_f"
    private const val CONFIRMADOS_70_79_M = "confirmados_70_79_m"
    private const val CONFIRMADOS_80_PLUS_F = "confirmados_80_plus_f"
    private const val CONFIRMADOS_80_PLUS_M = "confirmados_80_plus_m"
    private const val SINTOMAS_TOSSE = "sintomas_tosse"
    private const val SINTOMAS_FEBRE = "sintomas_febre"
    private const val SINTOMAS_DIFICULDADE_RESPIRATORIA = "sintomas_dificuldade_respiratoria"
    private const val SINTOMAS_CEFALEIA = "sintomas_cefaleia"
    private const val SINTOMAS_DORES_MUSCULARES = "sintomas_dores_musculares"
    private const val SINTOMAS_FRAQUEZA_GENERALIZADA = "sintomas_fraqueza_generalizada"
    private const val CONFIRMADOS_F = "confirmados_f"
    private const val CONFIRMADOS_M = "confirmados_m"
    private const val OBITOS_ARSNORTE = "obitos_arsnorte"
    private const val OBITOS_ARSCENTRO = "obitos_arscentro"
    private const val OBITOS_ARSLVT = "obitos_arslvt"
    private const val OBITOS_ARSALENTEJO = "obitos_arsalentejo"
    private const val OBITOS_ARSALGARVE = "obitos_arsalgarve"
    private const val OBITOS_ACORES = "obitos_acores"
    private const val OBITOS_MADEIRA = "obitos_madeira"
    private const val OBITOS_ESTRANGEIRO = "obitos_estrangeiro"
    private const val RECUPERADOS_ARSNORTE = "recuperados_arsnorte"
    private const val RECUPERADOS_ARSCENTRO = "recuperados_arscentro"
    private const val RECUPERADOS_ARSLVT = "recuperados_arslvt"
    private const val RECUPERADOS_ARSALENTEJO = "recuperados_arsalentejo"
    private const val RECUPERADOS_ARSALGARVE = "recuperados_arsalgarve"
    private const val RECUPERADOS_ACORES = "recuperados_acores"
    private const val RECUPERADOS_MADEIRA = "recuperados_madeira"
    private const val RECUPERADOS_ESTRANGEIRO = "recuperados_estrangeiro"
    private const val OBITOS_0_9_F = "obitos_0_9_f"
    private const val OBITOS_0_9_M = "obitos_0_9_m"
    private const val OBITOS_10_19_F = "obitos_10_19_f"
    private const val OBITOS_10_19_M = "obitos_10_19_m"
    private const val OBITOS_20_29_F = "obitos_20_29_f"
    private const val OBITOS_20_29_M = "obitos_20_29_m"
    private const val OBITOS_30_39_F = "obitos_30_39_f"
    private const val OBITOS_30_39_M = "obitos_30_39_m"
    private const val OBITOS_40_49_F = "obitos_40_49_f"
    private const val OBITOS_40_49_M = "obitos_40_49_m"
    private const val OBITOS_50_59_F = "obitos_50_59_f"
    private const val OBITOS_50_59_M = "obitos_50_59_m"
    private const val OBITOS_60_69_F = "obitos_60_69_f"
    private const val OBITOS_60_69_M = "obitos_60_69_m"
    private const val OBITOS_70_79_F = "obitos_70_79_f"
    private const val OBITOS_70_79_M = "obitos_70_79_m"
    private const val OBITOS_80_PLUS_F = "obitos_80_plus_f"
    private const val OBITOS_80_PLUS_M = "obitos_80_plus_m"
    private const val OBITOS_F = "obitos_f"
    private const val OBITOS_M = "obitos_m"
    private const val CONFIRMADOS_DESCONHECIDOS_M = "confirmados_desconhecidos_m"
    private const val CONFIRMADOS_DESCONHECIDOS_F = "confirmados_desconhecidos_f"
    private const val ATIVOS = "ativos"
    private const val INTERNADOS_ENFERMARIA = "internados_enfermaria"
    private const val CONFIRMADOS_DESCONHECIDOS = "confirmados_desconhecidos"
    private const val INCIDENCIA_NACIONAL = "incidencia_nacional"
    private const val INCIDENCIA_CONTINENTE = "incidencia_continente"
    private const val RT_NACIONAL = "rt_nacional"
    private const val RT_CONTINENTE = "rt_continente"

    fun mapCovid19PtRawData(rawData: List<Map<String, String>>): List<Data> =
        rawData.map { row ->
            Data(
                data = row[DATA].orEmpty(),
                data_dados = row[DATA_DADOS].orEmpty(),
                confirmados = getFloat(row[CONFIRMADOS]),
                confirmados_arsnorte = getFloat(row[CONFIRMADOS_ARSNORTE]),
                confirmados_arscentro = getFloat(row[CONFIRMADOS_ARSCENTRO]),
                confirmados_arslvt = getFloat(row[CONFIRMADOS_ARSLVT]),
                confirmados_arsalentejo = getFloat(row[CONFIRMADOS_ARSALENTEJO]),
                confirmados_arsalgarve = getFloat(row[CONFIRMADOS_ARSALGARVE]),
                confirmados_acores = getFloat(row[CONFIRMADOS_ACORES]),
                confirmados_madeira = getFloat(row[CONFIRMADOS_MADEIRA]),
                confirmados_estrangeiro = getFloat(row[CONFIRMADOS_ESTRANGEIRO]),
                confirmados_novos = getFloat(row[CONFIRMADOS_NOVOS]),
                recuperados = getFloat(row[RECUPERADOS]),
                obitos = getFloat(row[OBITOS]),
                internados = getFloat(row[INTERNADOS]),
                internados_uci = getFloat(row[INTERNADOS_UCI]),
                lab = getFloat(row[LAB]),
                suspeitos = getFloat(row[SUSPEITOS]),
                vigilancia = getFloat(row[VIGILANCIA]),
                n_confirmados = getFloat(row[N_CONFIRMADOS]),
                cadeias_transmissao = getFloat(row[CADEIAS_TRANSMISSAO]),
                transmissao_importada = getFloat(row[TRANSMISSAO_IMPORTADA]),
                confirmados_0_9_f = getFloat(row[CONFIRMADOS_0_9_F]),
                confirmados_0_9_m = getFloat(row[CONFIRMADOS_0_9_M]),
                confirmados_10_19_f = getFloat(row[CONFIRMADOS_10_19_F]),
                confirmados_10_19_m = getFloat(row[CONFIRMADOS_10_19_M]),
                confirmados_20_29_f = getFloat(row[CONFIRMADOS_20_29_F]),
                confirmados_20_29_m = getFloat(row[CONFIRMADOS_20_29_M]),
                confirmados_30_39_f = getFloat(row[CONFIRMADOS_30_39_F]),
                confirmados_30_39_m = getFloat(row[CONFIRMADOS_30_39_M]),
                confirmados_40_49_f = getFloat(row[CONFIRMADOS_40_49_F]),
                confirmados_40_49_m = getFloat(row[CONFIRMADOS_40_49_M]),
                confirmados_50_59_f = getFloat(row[CONFIRMADOS_50_59_F]),
                confirmados_50_59_m = getFloat(row[CONFIRMADOS_50_59_M]),
                confirmados_60_69_f = getFloat(row[CONFIRMADOS_60_69_F]),
                confirmados_60_69_m = getFloat(row[CONFIRMADOS_60_69_M]),
                confirmados_70_79_f = getFloat(row[CONFIRMADOS_70_79_F]),
                confirmados_70_79_m = getFloat(row[CONFIRMADOS_70_79_M]),
                confirmados_80_plus_f = getFloat(row[CONFIRMADOS_80_PLUS_F]),
                confirmados_80_plus_m = getFloat(row[CONFIRMADOS_80_PLUS_M]),
                sintomas_tosse = getFloat(row[SINTOMAS_TOSSE]),
                sintomas_febre = getFloat(row[SINTOMAS_FEBRE]),
                sintomas_dificuldade_respiratoria = getFloat(row[SINTOMAS_DIFICULDADE_RESPIRATORIA]),
                sintomas_cefaleia = getFloat(row[SINTOMAS_CEFALEIA]),
                sintomas_dores_musculares = getFloat(row[SINTOMAS_DORES_MUSCULARES]),
                sintomas_fraqueza_generalizada = getFloat(row[SINTOMAS_FRAQUEZA_GENERALIZADA]),
                confirmados_f = getFloat(row[CONFIRMADOS_F]),
                confirmados_m = getFloat(row[CONFIRMADOS_M]),
                obitos_arsnorte = getFloat(row[OBITOS_ARSNORTE]),
                obitos_arscentro = getFloat(row[OBITOS_ARSCENTRO]),
                obitos_arslvt = getFloat(row[OBITOS_ARSLVT]),
                obitos_arsalentejo = getFloat(row[OBITOS_ARSALENTEJO]),
                obitos_arsalgarve = getFloat(row[OBITOS_ARSALGARVE]),
                obitos_acores = getFloat(row[OBITOS_ACORES]),
                obitos_madeira = getFloat(row[OBITOS_MADEIRA]),
                obitos_estrangeiro = getFloat(row[OBITOS_ESTRANGEIRO]),
                recuperados_arsnorte = getFloat(row[RECUPERADOS_ARSNORTE]),
                recuperados_arscentro = getFloat(row[RECUPERADOS_ARSCENTRO]),
                recuperados_arslvt = getFloat(row[RECUPERADOS_ARSLVT]),
                recuperados_arsalentejo = getFloat(row[RECUPERADOS_ARSALENTEJO]),
                recuperados_arsalgarve = getFloat(row[RECUPERADOS_ARSALGARVE]),
                recuperados_acores = getFloat(row[RECUPERADOS_ACORES]),
                recuperados_madeira = getFloat(row[RECUPERADOS_MADEIRA]),
                recuperados_estrangeiro = getFloat(row[RECUPERADOS_ESTRANGEIRO]),
                obitos_0_9_f = getFloat(row[OBITOS_0_9_F]),
                obitos_0_9_m = getFloat(row[OBITOS_0_9_M]),
                obitos_10_19_f = getFloat(row[OBITOS_10_19_F]),
                obitos_10_19_m = getFloat(row[OBITOS_10_19_M]),
                obitos_20_29_f = getFloat(row[OBITOS_20_29_F]),
                obitos_20_29_m = getFloat(row[OBITOS_20_29_M]),
                obitos_30_39_f = getFloat(row[OBITOS_30_39_F]),
                obitos_30_39_m = getFloat(row[OBITOS_30_39_M]),
                obitos_40_49_f = getFloat(row[OBITOS_40_49_F]),
                obitos_40_49_m = getFloat(row[OBITOS_40_49_M]),
                obitos_50_59_f = getFloat(row[OBITOS_50_59_F]),
                obitos_50_59_m = getFloat(row[OBITOS_50_59_M]),
                obitos_60_69_f = getFloat(row[OBITOS_60_69_F]),
                obitos_60_69_m = getFloat(row[OBITOS_60_69_M]),
                obitos_70_79_f = getFloat(row[OBITOS_70_79_F]),
                obitos_70_79_m = getFloat(row[OBITOS_70_79_M]),
                obitos_80_plus_f = getFloat(row[OBITOS_80_PLUS_F]),
                obitos_80_plus_m = getFloat(row[OBITOS_80_PLUS_M]),
                obitos_f = getFloat(row[OBITOS_F]),
                obitos_m = getFloat(row[OBITOS_M]),
                confirmados_desconhecidos_m = getFloat(row[CONFIRMADOS_DESCONHECIDOS_M]),
                confirmados_desconhecidos_f = getFloat(row[CONFIRMADOS_DESCONHECIDOS_F]),
                ativos = getFloat(row[ATIVOS]),
                internados_enfermaria = getFloat(row[INTERNADOS_ENFERMARIA]),
                confirmados_desconhecidos = getFloat(row[CONFIRMADOS_DESCONHECIDOS]),
                incidencia_nacional = getFloat(row[INCIDENCIA_NACIONAL]),
                incidencia_continente = getFloat(row[INCIDENCIA_CONTINENTE]),
                rt_nacional = getFloat(row[RT_NACIONAL]),
                rt_continente = getFloat(row[RT_CONTINENTE]),
            )
        }

    private fun getFloat(parameter: String?): Float {
        return parameter?.toFloatOrNull() ?: 0F
    }
}



