package com.sousajrps.covid19pt.remote.mappers

import com.sousajrps.covid19pt.remote.models.VaccinationWeekly

object VaccinationWeeklyMapper {
    private const val DATA = "data"
    private const val RECEBIDAS = "recebidas"
    private const val DISTRIBUIDAS = "distribuidas"
    private const val DOSES = "doses"
    private const val DOSES_NOVAS = "doses_novas"
    private const val DOSES1 = "doses1"
    private const val DOSES1_NOVAS = "doses1_novas"
    private const val DOSES2 = "doses2"
    private const val DOSES2_NOVAS = "doses2_novas"
    private const val DOSESUNK = "dosesunk"
    private const val DOSESUNK_NOVAS = "dosesunk_novas"
    private const val DOSES1_PERC = "doses1_perc"
    private const val DOSES2_PERC = "doses2_perc"
    private const val POPULACAO1 = "populacao1"
    private const val POPULACAO2 = "populacao2"
    private const val DOSES_CONTINENTE = "doses_continente"
    private const val DOSES_NOVAS_CONTINENTE = "doses_novas_continente"
    private const val DOSES1_CONTINENTE = "doses1_continente"
    private const val DOSES1_NOVAS_CONTINENTE = "doses1_novas_continente"
    private const val DOSES2_CONTINENTE = "doses2_continente"
    private const val DOSES2_NOVAS_CONTINENTE = "doses2_novas_continente"
    private const val DOSESUNK_CONTINENTE = "dosesunk_continente"
    private const val DOSESUNK_NOVAS_CONTINENTE = "dosesunk_novas_continente"
    private const val DOSES1_PERC_CONTINENTE = "doses1_perc_continente"
    private const val DOSES2_PERC_CONTINENTE = "doses2_perc_continente"
    private const val POPULACAO1_CONTINENTE = "populacao1_continente"
    private const val POPULACAO2_CONTINENTE = "populacao2_continente"
    private const val DOSES_ARSNORTE = "doses_arsnorte"
    private const val DOSES_NOVAS_ARSNORTE = "doses_novas_arsnorte"
    private const val DOSES1_ARSNORTE = "doses1_arsnorte"
    private const val DOSES1_NOVAS_ARSNORTE = "doses1_novas_arsnorte"
    private const val DOSES2_ARSNORTE = "doses2_arsnorte"
    private const val DOSES2_NOVAS_ARSNORTE = "doses2_novas_arsnorte"
    private const val DOSESUNK_ARSNORTE = "dosesunk_arsnorte"
    private const val DOSESUNK_NOVAS_ARSNORTE = "dosesunk_novas_arsnorte"
    private const val DOSES1_PERC_ARSNORTE = "doses1_perc_arsnorte"
    private const val DOSES2_PERC_ARSNORTE = "doses2_perc_arsnorte"
    private const val POPULACAO1_ARSNORTE = "populacao1_arsnorte"
    private const val POPULACAO2_ARSNORTE = "populacao2_arsnorte"
    private const val DOSES_ARSCENTRO = "doses_arscentro"
    private const val DOSES_NOVAS_ARSCENTRO = "doses_novas_arscentro"
    private const val DOSES1_ARSCENTRO = "doses1_arscentro"
    private const val DOSES1_NOVAS_ARSCENTRO = "doses1_novas_arscentro"
    private const val DOSES2_ARSCENTRO = "doses2_arscentro"
    private const val DOSES2_NOVAS_ARSCENTRO = "doses2_novas_arscentro"
    private const val DOSESUNK_ARSCENTRO = "dosesunk_arscentro"
    private const val DOSESUNK_NOVAS_ARSCENTRO = "dosesunk_novas_arscentro"
    private const val DOSES1_PERC_ARSCENTRO = "doses1_perc_arscentro"
    private const val DOSES2_PERC_ARSCENTRO = "doses2_perc_arscentro"
    private const val POPULACAO1_ARSCENTRO = "populacao1_arscentro"
    private const val POPULACAO2_ARSCENTRO = "populacao2_arscentro"
    private const val DOSES_ARSLVT = "doses_arslvt"
    private const val DOSES_NOVAS_ARSLVT = "doses_novas_arslvt"
    private const val DOSES1_ARSLVT = "doses1_arslvt"
    private const val DOSES1_NOVAS_ARSLVT = "doses1_novas_arslvt"
    private const val DOSES2_ARSLVT = "doses2_arslvt"
    private const val DOSES2_NOVAS_ARSLVT = "doses2_novas_arslvt"
    private const val DOSESUNK_ARSLVT = "dosesunk_arslvt"
    private const val DOSESUNK_NOVAS_ARSLVT = "dosesunk_novas_arslvt"
    private const val DOSES1_PERC_ARSLVT = "doses1_perc_arslvt"
    private const val DOSES2_PERC_ARSLVT = "doses2_perc_arslvt"
    private const val POPULACAO1_ARSLVT = "populacao1_arslvt"
    private const val POPULACAO2_ARSLVT = "populacao2_arslvt"
    private const val DOSES_ARSALENTEJO = "doses_arsalentejo"
    private const val DOSES_NOVAS_ARSALENTEJO = "doses_novas_arsalentejo"
    private const val DOSES1_ARSALENTEJO = "doses1_arsalentejo"
    private const val DOSES1_NOVAS_ARSALENTEJO = "doses1_novas_arsalentejo"
    private const val DOSES2_ARSALENTEJO = "doses2_arsalentejo"
    private const val DOSES2_NOVAS_ARSALENTEJO = "doses2_novas_arsalentejo"
    private const val DOSESUNK_ARSALENTEJO = "dosesunk_arsalentejo"
    private const val DOSESUNK_NOVAS_ARSALENTEJO = "dosesunk_novas_arsalentejo"
    private const val DOSES1_PERC_ARSALENTEJO = "doses1_perc_arsalentejo"
    private const val DOSES2_PERC_ARSALENTEJO = "doses2_perc_arsalentejo"
    private const val POPULACAO1_ARSALENTEJO = "populacao1_arsalentejo"
    private const val POPULACAO2_ARSALENTEJO = "populacao2_arsalentejo"
    private const val DOSES_ARSALGARVE = "doses_arsalgarve"
    private const val DOSES_NOVAS_ARSALGARVE = "doses_novas_arsalgarve"
    private const val DOSES1_ARSALGARVE = "doses1_arsalgarve"
    private const val DOSES1_NOVAS_ARSALGARVE = "doses1_novas_arsalgarve"
    private const val DOSES2_ARSALGARVE = "doses2_arsalgarve"
    private const val DOSES2_NOVAS_ARSALGARVE = "doses2_novas_arsalgarve"
    private const val DOSESUNK_ARSALGARVE = "dosesunk_arsalgarve"
    private const val DOSESUNK_NOVAS_ARSALGARVE = "dosesunk_novas_arsalgarve"
    private const val DOSES1_PERC_ARSALGARVE = "doses1_perc_arsalgarve"
    private const val DOSES2_PERC_ARSALGARVE = "doses2_perc_arsalgarve"
    private const val POPULACAO1_ARSALGARVE = "populacao1_arsalgarve"
    private const val POPULACAO2_ARSALGARVE = "populacao2_arsalgarve"
    private const val DOSES_MADEIRA = "doses_madeira"
    private const val DOSES_NOVAS_MADEIRA = "doses_novas_madeira"
    private const val DOSES1_MADEIRA = "doses1_madeira"
    private const val DOSES1_NOVAS_MADEIRA = "doses1_novas_madeira"
    private const val DOSES2_MADEIRA = "doses2_madeira"
    private const val DOSES2_NOVAS_MADEIRA = "doses2_novas_madeira"
    private const val DOSESUNK_MADEIRA = "dosesunk_madeira"
    private const val DOSESUNK_NOVAS_MADEIRA = "dosesunk_novas_madeira"
    private const val DOSES1_PERC_MADEIRA = "doses1_perc_madeira"
    private const val DOSES2_PERC_MADEIRA = "doses2_perc_madeira"
    private const val POPULACAO1_MADEIRA = "populacao1_madeira"
    private const val POPULACAO2_MADEIRA = "populacao2_madeira"
    private const val DOSES_AcORES = "doses_açores"
    private const val DOSES_NOVAS_AcORES = "doses_novas_açores"
    private const val DOSES1_AcORES = "doses1_açores"
    private const val DOSES1_NOVAS_AcORES = "doses1_novas_açores"
    private const val DOSES2_AcORES = "doses2_açores"
    private const val DOSES2_NOVAS_AcORES = "doses2_novas_açores"
    private const val DOSESUNK_AcORES = "dosesunk_açores"
    private const val DOSESUNK_NOVAS_AcORES = "dosesunk_novas_açores"
    private const val DOSES1_PERC_AcORES = "doses1_perc_açores"
    private const val DOSES2_PERC_AcORES = "doses2_perc_açores"
    private const val POPULACAO1_AcORES = "populacao1_açores"
    private const val POPULACAO2_AcORES = "populacao2_açores"
    private const val DOSES_OUTRO = "doses_outro"
    private const val DOSES_NOVAS_OUTRO = "doses_novas_outro"
    private const val DOSES1_OUTRO = "doses1_outro"
    private const val DOSES1_NOVAS_OUTRO = "doses1_novas_outro"
    private const val DOSES2_OUTRO = "doses2_outro"
    private const val DOSES2_NOVAS_OUTRO = "doses2_novas_outro"
    private const val DOSESUNK_OUTRO = "dosesunk_outro"
    private const val DOSESUNK_NOVAS_OUTRO = "dosesunk_novas_outro"
    private const val DOSES_0_17 = "doses_0_17"
    private const val DOSES_NOVAS_0_17 = "doses_novas_0_17"
    private const val DOSES1_0_17 = "doses1_0_17"
    private const val DOSES1_NOVAS_0_17 = "doses1_novas_0_17"
    private const val DOSES2_0_17 = "doses2_0_17"
    private const val DOSES2_NOVAS_0_17 = "doses2_novas_0_17"
    private const val DOSESUNK_0_17 = "dosesunk_0_17"
    private const val DOSESUNK_NOVAS_0_17 = "dosesunk_novas_0_17"
    private const val DOSES1_PERC_0_17 = "doses1_perc_0_17"
    private const val DOSES2_PERC_0_17 = "doses2_perc_0_17"
    private const val POPULACAO1_0_17 = "populacao1_0_17"
    private const val POPULACAO2_0_17 = "populacao2_0_17"
    private const val DOSES_18_24 = "doses_18_24"
    private const val DOSES_NOVAS_18_24 = "doses_novas_18_24"
    private const val DOSES1_18_24 = "doses1_18_24"
    private const val DOSES1_NOVAS_18_24 = "doses1_novas_18_24"
    private const val DOSES2_18_24 = "doses2_18_24"
    private const val DOSES2_NOVAS_18_24 = "doses2_novas_18_24"
    private const val DOSESUNK_18_24 = "dosesunk_18_24"
    private const val DOSESUNK_NOVAS_18_24 = "dosesunk_novas_18_24"
    private const val DOSES1_PERC_18_24 = "doses1_perc_18_24"
    private const val DOSES2_PERC_18_24 = "doses2_perc_18_24"
    private const val POPULACAO1_18_24 = "populacao1_18_24"
    private const val POPULACAO2_18_24 = "populacao2_18_24"
    private const val DOSES_25_49 = "doses_25_49"
    private const val DOSES_NOVAS_25_49 = "doses_novas_25_49"
    private const val DOSES1_25_49 = "doses1_25_49"
    private const val DOSES1_NOVAS_25_49 = "doses1_novas_25_49"
    private const val DOSES2_25_49 = "doses2_25_49"
    private const val DOSES2_NOVAS_25_49 = "doses2_novas_25_49"
    private const val DOSESUNK_25_49 = "dosesunk_25_49"
    private const val DOSESUNK_NOVAS_25_49 = "dosesunk_novas_25_49"
    private const val DOSES1_PERC_25_49 = "doses1_perc_25_49"
    private const val DOSES2_PERC_25_49 = "doses2_perc_25_49"
    private const val POPULACAO1_25_49 = "populacao1_25_49"
    private const val POPULACAO2_25_49 = "populacao2_25_49"
    private const val DOSES_50_64 = "doses_50_64"
    private const val DOSES_NOVAS_50_64 = "doses_novas_50_64"
    private const val DOSES1_50_64 = "doses1_50_64"
    private const val DOSES1_NOVAS_50_64 = "doses1_novas_50_64"
    private const val DOSES2_50_64 = "doses2_50_64"
    private const val DOSES2_NOVAS_50_64 = "doses2_novas_50_64"
    private const val DOSESUNK_50_64 = "dosesunk_50_64"
    private const val DOSESUNK_NOVAS_50_64 = "dosesunk_novas_50_64"
    private const val DOSES1_PERC_50_64 = "doses1_perc_50_64"
    private const val DOSES2_PERC_50_64 = "doses2_perc_50_64"
    private const val POPULACAO1_50_64 = "populacao1_50_64"
    private const val POPULACAO2_50_64 = "populacao2_50_64"
    private const val DOSES_65_79 = "doses_65_79"
    private const val DOSES_NOVAS_65_79 = "doses_novas_65_79"
    private const val DOSES1_65_79 = "doses1_65_79"
    private const val DOSES1_NOVAS_65_79 = "doses1_novas_65_79"
    private const val DOSES2_65_79 = "doses2_65_79"
    private const val DOSES2_NOVAS_65_79 = "doses2_novas_65_79"
    private const val DOSESUNK_65_79 = "dosesunk_65_79"
    private const val DOSESUNK_NOVAS_65_79 = "dosesunk_novas_65_79"
    private const val DOSES1_PERC_65_79 = "doses1_perc_65_79"
    private const val DOSES2_PERC_65_79 = "doses2_perc_65_79"
    private const val POPULACAO1_65_79 = "populacao1_65_79"
    private const val POPULACAO2_65_79 = "populacao2_65_79"
    private const val DOSES_80 = "doses_80+"
    private const val DOSES_NOVAS_80 = "doses_novas_80+"
    private const val DOSES1_80 = "doses1_80+"
    private const val DOSES1_NOVAS_80 = "doses1_novas_80+"
    private const val DOSES2_80 = "doses2_80+"
    private const val DOSES2_NOVAS_80 = "doses2_novas_80+"
    private const val DOSESUNK_80 = "dosesunk_80+"
    private const val DOSESUNK_NOVAS_80 = "dosesunk_novas_80+"
    private const val DOSES1_PERC_80 = "doses1_perc_80+"
    private const val DOSES2_PERC_80 = "doses2_perc_80+"
    private const val POPULACAO1_80 = "populacao1_80+"
    private const val POPULACAO2_80 = "populacao2_80+"
    private const val DOSES_DESCONHECIDO = "doses_desconhecido"
    private const val DOSES_NOVAS_DESCONHECIDO = "doses_novas_desconhecido"
    private const val DOSES1_DESCONHECIDO = "doses1_desconhecido"
    private const val DOSES1_NOVAS_DESCONHECIDO = "doses1_novas_desconhecido"
    private const val DOSES2_DESCONHECIDO = "doses2_desconhecido"
    private const val DOSES2_NOVAS_DESCONHECIDO = "doses2_novas_desconhecido"
    private const val DOSESUNK_DESCONHECIDO = "dosesunk_desconhecido"
    private const val DOSESUNK_NOVAS_DESCONHECIDO = "dosesunk_novas_desconhecido"

    fun mapVaccinationWeeklyRawData(rawData: List<Map<String, String>>): List<VaccinationWeekly> =
        rawData.map { row ->
            VaccinationWeekly(
                data = row[DATA].orEmpty(),
                recebidas = getFloat(row[RECEBIDAS]),
                distribuidas = getFloat(row[DISTRIBUIDAS]),
                doses = getFloat(row[DOSES]),
                doses_novas = getFloat(row[DOSES_NOVAS]),
                doses1 = getFloat(row[DOSES1]),
                doses1_novas = getFloat(row[DOSES1_NOVAS]),
                doses2 = getFloat(row[DOSES2]),
                doses2_novas = getFloat(row[DOSES2_NOVAS]),
                dosesunk = getFloat(row[DOSESUNK]),
                dosesunk_novas = getFloat(row[DOSESUNK_NOVAS]),
                doses1_perc = getFloat(row[DOSES1_PERC]),
                doses2_perc = getFloat(row[DOSES2_PERC]),
                populacao1 = getFloat(row[POPULACAO1]),
                populacao2 = getFloat(row[POPULACAO2]),
                doses_continente = getFloat(row[DOSES_CONTINENTE]),
                doses_novas_continente = getFloat(row[DOSES_NOVAS_CONTINENTE]),
                doses1_continente = getFloat(row[DOSES1_CONTINENTE]),
                doses1_novas_continente = getFloat(row[DOSES1_NOVAS_CONTINENTE]),
                doses2_continente = getFloat(row[DOSES2_CONTINENTE]),
                doses2_novas_continente = getFloat(row[DOSES2_NOVAS_CONTINENTE]),
                dosesunk_continente = getFloat(row[DOSESUNK_CONTINENTE]),
                dosesunk_novas_continente = getFloat(row[DOSESUNK_NOVAS_CONTINENTE]),
                doses1_perc_continente = getFloat(row[DOSES1_PERC_CONTINENTE]),
                doses2_perc_continente = getFloat(row[DOSES2_PERC_CONTINENTE]),
                populacao1_continente = getFloat(row[POPULACAO1_CONTINENTE]),
                populacao2_continente = getFloat(row[POPULACAO2_CONTINENTE]),
                doses_arsnorte = getFloat(row[DOSES_ARSNORTE]),
                doses_novas_arsnorte = getFloat(row[DOSES_NOVAS_ARSNORTE]),
                doses1_arsnorte = getFloat(row[DOSES1_ARSNORTE]),
                doses1_novas_arsnorte = getFloat(row[DOSES1_NOVAS_ARSNORTE]),
                doses2_arsnorte = getFloat(row[DOSES2_ARSNORTE]),
                doses2_novas_arsnorte = getFloat(row[DOSES2_NOVAS_ARSNORTE]),
                dosesunk_arsnorte = getFloat(row[DOSESUNK_ARSNORTE]),
                dosesunk_novas_arsnorte = getFloat(row[DOSESUNK_NOVAS_ARSNORTE]),
                doses1_perc_arsnorte = getFloat(row[DOSES1_PERC_ARSNORTE]),
                doses2_perc_arsnorte = getFloat(row[DOSES2_PERC_ARSNORTE]),
                populacao1_arsnorte = getFloat(row[POPULACAO1_ARSNORTE]),
                populacao2_arsnorte = getFloat(row[POPULACAO2_ARSNORTE]),
                doses_arscentro = getFloat(row[DOSES_ARSCENTRO]),
                doses_novas_arscentro = getFloat(row[DOSES_NOVAS_ARSCENTRO]),
                doses1_arscentro = getFloat(row[DOSES1_ARSCENTRO]),
                doses1_novas_arscentro = getFloat(row[DOSES1_NOVAS_ARSCENTRO]),
                doses2_arscentro = getFloat(row[DOSES2_ARSCENTRO]),
                doses2_novas_arscentro = getFloat(row[DOSES2_NOVAS_ARSCENTRO]),
                dosesunk_arscentro = getFloat(row[DOSESUNK_ARSCENTRO]),
                dosesunk_novas_arscentro = getFloat(row[DOSESUNK_NOVAS_ARSCENTRO]),
                doses1_perc_arscentro = getFloat(row[DOSES1_PERC_ARSCENTRO]),
                doses2_perc_arscentro = getFloat(row[DOSES2_PERC_ARSCENTRO]),
                populacao1_arscentro = getFloat(row[POPULACAO1_ARSCENTRO]),
                populacao2_arscentro = getFloat(row[POPULACAO2_ARSCENTRO]),
                doses_arslvt = getFloat(row[DOSES_ARSLVT]),
                doses_novas_arslvt = getFloat(row[DOSES_NOVAS_ARSLVT]),
                doses1_arslvt = getFloat(row[DOSES1_ARSLVT]),
                doses1_novas_arslvt = getFloat(row[DOSES1_NOVAS_ARSLVT]),
                doses2_arslvt = getFloat(row[DOSES2_ARSLVT]),
                doses2_novas_arslvt = getFloat(row[DOSES2_NOVAS_ARSLVT]),
                dosesunk_arslvt = getFloat(row[DOSESUNK_ARSLVT]),
                dosesunk_novas_arslvt = getFloat(row[DOSESUNK_NOVAS_ARSLVT]),
                doses1_perc_arslvt = getFloat(row[DOSES1_PERC_ARSLVT]),
                doses2_perc_arslvt = getFloat(row[DOSES2_PERC_ARSLVT]),
                populacao1_arslvt = getFloat(row[POPULACAO1_ARSLVT]),
                populacao2_arslvt = getFloat(row[POPULACAO2_ARSLVT]),
                doses_arsalentejo = getFloat(row[DOSES_ARSALENTEJO]),
                doses_novas_arsalentejo = getFloat(row[DOSES_NOVAS_ARSALENTEJO]),
                doses1_arsalentejo = getFloat(row[DOSES1_ARSALENTEJO]),
                doses1_novas_arsalentejo = getFloat(row[DOSES1_NOVAS_ARSALENTEJO]),
                doses2_arsalentejo = getFloat(row[DOSES2_ARSALENTEJO]),
                doses2_novas_arsalentejo = getFloat(row[DOSES2_NOVAS_ARSALENTEJO]),
                dosesunk_arsalentejo = getFloat(row[DOSESUNK_ARSALENTEJO]),
                dosesunk_novas_arsalentejo = getFloat(row[DOSESUNK_NOVAS_ARSALENTEJO]),
                doses1_perc_arsalentejo = getFloat(row[DOSES1_PERC_ARSALENTEJO]),
                doses2_perc_arsalentejo = getFloat(row[DOSES2_PERC_ARSALENTEJO]),
                populacao1_arsalentejo = getFloat(row[POPULACAO1_ARSALENTEJO]),
                populacao2_arsalentejo = getFloat(row[POPULACAO2_ARSALENTEJO]),
                doses_arsalgarve = getFloat(row[DOSES_ARSALGARVE]),
                doses_novas_arsalgarve = getFloat(row[DOSES_NOVAS_ARSALGARVE]),
                doses1_arsalgarve = getFloat(row[DOSES1_ARSALGARVE]),
                doses1_novas_arsalgarve = getFloat(row[DOSES1_NOVAS_ARSALGARVE]),
                doses2_arsalgarve = getFloat(row[DOSES2_ARSALGARVE]),
                doses2_novas_arsalgarve = getFloat(row[DOSES2_NOVAS_ARSALGARVE]),
                dosesunk_arsalgarve = getFloat(row[DOSESUNK_ARSALGARVE]),
                dosesunk_novas_arsalgarve = getFloat(row[DOSESUNK_NOVAS_ARSALGARVE]),
                doses1_perc_arsalgarve = getFloat(row[DOSES1_PERC_ARSALGARVE]),
                doses2_perc_arsalgarve = getFloat(row[DOSES2_PERC_ARSALGARVE]),
                populacao1_arsalgarve = getFloat(row[POPULACAO1_ARSALGARVE]),
                populacao2_arsalgarve = getFloat(row[POPULACAO2_ARSALGARVE]),
                doses_madeira = getFloat(row[DOSES_MADEIRA]),
                doses_novas_madeira = getFloat(row[DOSES_NOVAS_MADEIRA]),
                doses1_madeira = getFloat(row[DOSES1_MADEIRA]),
                doses1_novas_madeira = getFloat(row[DOSES1_NOVAS_MADEIRA]),
                doses2_madeira = getFloat(row[DOSES2_MADEIRA]),
                doses2_novas_madeira = getFloat(row[DOSES2_NOVAS_MADEIRA]),
                dosesunk_madeira = getFloat(row[DOSESUNK_MADEIRA]),
                dosesunk_novas_madeira = getFloat(row[DOSESUNK_NOVAS_MADEIRA]),
                doses1_perc_madeira = getFloat(row[DOSES1_PERC_MADEIRA]),
                doses2_perc_madeira = getFloat(row[DOSES2_PERC_MADEIRA]),
                populacao1_madeira = getFloat(row[POPULACAO1_MADEIRA]),
                populacao2_madeira = getFloat(row[POPULACAO2_MADEIRA]),
                doses_acores = getFloat(row[DOSES_AcORES]),
                doses_novas_acores = getFloat(row[DOSES_NOVAS_AcORES]),
                doses1_acores = getFloat(row[DOSES1_AcORES]),
                doses1_novas_acores = getFloat(row[DOSES1_NOVAS_AcORES]),
                doses2_acores = getFloat(row[DOSES2_AcORES]),
                doses2_novas_acores = getFloat(row[DOSES2_NOVAS_AcORES]),
                dosesunk_acores = getFloat(row[DOSESUNK_AcORES]),
                dosesunk_novas_acores = getFloat(row[DOSESUNK_NOVAS_AcORES]),
                doses1_perc_acores = getFloat(row[DOSES1_PERC_AcORES]),
                doses2_perc_acores = getFloat(row[DOSES2_PERC_AcORES]),
                populacao1_acores = getFloat(row[POPULACAO1_AcORES]),
                populacao2_acores = getFloat(row[POPULACAO2_AcORES]),
                doses_outro = getFloat(row[DOSES_OUTRO]),
                doses_novas_outro = getFloat(row[DOSES_NOVAS_OUTRO]),
                doses1_outro = getFloat(row[DOSES1_OUTRO]),
                doses1_novas_outro = getFloat(row[DOSES1_NOVAS_OUTRO]),
                doses2_outro = getFloat(row[DOSES2_OUTRO]),
                doses2_novas_outro = getFloat(row[DOSES2_NOVAS_OUTRO]),
                dosesunk_outro = getFloat(row[DOSESUNK_OUTRO]),
                dosesunk_novas_outro = getFloat(row[DOSESUNK_NOVAS_OUTRO]),
                doses_0_17 = getFloat(row[DOSES_0_17]),
                doses_novas_0_17 = getFloat(row[DOSES_NOVAS_0_17]),
                doses1_0_17 = getFloat(row[DOSES1_0_17]),
                doses1_novas_0_17 = getFloat(row[DOSES1_NOVAS_0_17]),
                doses2_0_17 = getFloat(row[DOSES2_0_17]),
                doses2_novas_0_17 = getFloat(row[DOSES2_NOVAS_0_17]),
                dosesunk_0_17 = getFloat(row[DOSESUNK_0_17]),
                dosesunk_novas_0_17 = getFloat(row[DOSESUNK_NOVAS_0_17]),
                doses1_perc_0_17 = getFloat(row[DOSES1_PERC_0_17]),
                doses2_perc_0_17 = getFloat(row[DOSES2_PERC_0_17]),
                populacao1_0_17 = getFloat(row[POPULACAO1_0_17]),
                populacao2_0_17 = getFloat(row[POPULACAO2_0_17]),
                doses_18_24 = getFloat(row[DOSES_18_24]),
                doses_novas_18_24 = getFloat(row[DOSES_NOVAS_18_24]),
                doses1_18_24 = getFloat(row[DOSES1_18_24]),
                doses1_novas_18_24 = getFloat(row[DOSES1_NOVAS_18_24]),
                doses2_18_24 = getFloat(row[DOSES2_18_24]),
                doses2_novas_18_24 = getFloat(row[DOSES2_NOVAS_18_24]),
                dosesunk_18_24 = getFloat(row[DOSESUNK_18_24]),
                dosesunk_novas_18_24 = getFloat(row[DOSESUNK_NOVAS_18_24]),
                doses1_perc_18_24 = getFloat(row[DOSES1_PERC_18_24]),
                doses2_perc_18_24 = getFloat(row[DOSES2_PERC_18_24]),
                populacao1_18_24 = getFloat(row[POPULACAO1_18_24]),
                populacao2_18_24 = getFloat(row[POPULACAO2_18_24]),
                doses_25_49 = getFloat(row[DOSES_25_49]),
                doses_novas_25_49 = getFloat(row[DOSES_NOVAS_25_49]),
                doses1_25_49 = getFloat(row[DOSES1_25_49]),
                doses1_novas_25_49 = getFloat(row[DOSES1_NOVAS_25_49]),
                doses2_25_49 = getFloat(row[DOSES2_25_49]),
                doses2_novas_25_49 = getFloat(row[DOSES2_NOVAS_25_49]),
                dosesunk_25_49 = getFloat(row[DOSESUNK_25_49]),
                dosesunk_novas_25_49 = getFloat(row[DOSESUNK_NOVAS_25_49]),
                doses1_perc_25_49 = getFloat(row[DOSES1_PERC_25_49]),
                doses2_perc_25_49 = getFloat(row[DOSES2_PERC_25_49]),
                populacao1_25_49 = getFloat(row[POPULACAO1_25_49]),
                populacao2_25_49 = getFloat(row[POPULACAO2_25_49]),
                doses_50_64 = getFloat(row[DOSES_50_64]),
                doses_novas_50_64 = getFloat(row[DOSES_NOVAS_50_64]),
                doses1_50_64 = getFloat(row[DOSES1_50_64]),
                doses1_novas_50_64 = getFloat(row[DOSES1_NOVAS_50_64]),
                doses2_50_64 = getFloat(row[DOSES2_50_64]),
                doses2_novas_50_64 = getFloat(row[DOSES2_NOVAS_50_64]),
                dosesunk_50_64 = getFloat(row[DOSESUNK_50_64]),
                dosesunk_novas_50_64 = getFloat(row[DOSESUNK_NOVAS_50_64]),
                doses1_perc_50_64 = getFloat(row[DOSES1_PERC_50_64]),
                doses2_perc_50_64 = getFloat(row[DOSES2_PERC_50_64]),
                populacao1_50_64 = getFloat(row[POPULACAO1_50_64]),
                populacao2_50_64 = getFloat(row[POPULACAO2_50_64]),
                doses_65_79 = getFloat(row[DOSES_65_79]),
                doses_novas_65_79 = getFloat(row[DOSES_NOVAS_65_79]),
                doses1_65_79 = getFloat(row[DOSES1_65_79]),
                doses1_novas_65_79 = getFloat(row[DOSES1_NOVAS_65_79]),
                doses2_65_79 = getFloat(row[DOSES2_65_79]),
                doses2_novas_65_79 = getFloat(row[DOSES2_NOVAS_65_79]),
                dosesunk_65_79 = getFloat(row[DOSESUNK_65_79]),
                dosesunk_novas_65_79 = getFloat(row[DOSESUNK_NOVAS_65_79]),
                doses1_perc_65_79 = getFloat(row[DOSES1_PERC_65_79]),
                doses2_perc_65_79 = getFloat(row[DOSES2_PERC_65_79]),
                populacao1_65_79 = getFloat(row[POPULACAO1_65_79]),
                populacao2_65_79 = getFloat(row[POPULACAO2_65_79]),
                doses_80 = getFloat(row[DOSES_80]),
                doses_novas_80 = getFloat(row[DOSES_NOVAS_80]),
                doses1_80 = getFloat(row[DOSES1_80]),
                doses1_novas_80 = getFloat(row[DOSES1_NOVAS_80]),
                doses2_80 = getFloat(row[DOSES2_80]),
                doses2_novas_80 = getFloat(row[DOSES2_NOVAS_80]),
                dosesunk_80 = getFloat(row[DOSESUNK_80]),
                dosesunk_novas_80 = getFloat(row[DOSESUNK_NOVAS_80]),
                doses1_perc_80 = getFloat(row[DOSES1_PERC_80]),
                doses2_perc_80 = getFloat(row[DOSES2_PERC_80]),
                populacao1_80 = getFloat(row[POPULACAO1_80]),
                populacao2_80 = getFloat(row[POPULACAO2_80]),
                doses_desconhecido = getFloat(row[DOSES_DESCONHECIDO]),
                doses_novas_desconhecido = getFloat(row[DOSES_NOVAS_DESCONHECIDO]),
                doses1_desconhecido = getFloat(row[DOSES1_DESCONHECIDO]),
                doses1_novas_desconhecido = getFloat(row[DOSES1_NOVAS_DESCONHECIDO]),
                doses2_desconhecido = getFloat(row[DOSES2_DESCONHECIDO]),
                doses2_novas_desconhecido = getFloat(row[DOSES2_NOVAS_DESCONHECIDO]),
                dosesunk_desconhecido = getFloat(row[DOSESUNK_DESCONHECIDO]),
                dosesunk_novas_desconhecido = getFloat(row[DOSESUNK_NOVAS_DESCONHECIDO]),
            )
        }

    private fun getFloat(parameter: String?): Float {
        return parameter?.toFloatOrNull() ?: 0F
    }
}
